// <auto-generated />
using System;
using ARSAN_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARSAN_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023205143_AgregarIdClusterAMulta")]
    partial class AgregarIdClusterAMulta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ARSAN_Web.Models.AccesoVehicular", b =>
                {
                    b.Property<int>("IdAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_acceso");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_salida");

                    b.Property<TimeSpan>("HoraIngreso")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_ingreso");

                    b.Property<TimeSpan?>("HoraSalida")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_salida");

                    b.Property<int>("IdGarita")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_garita");

                    b.Property<int>("IdGuardiaIngreso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_guardia_ingreso");

                    b.Property<int?>("IdGuardiaSalida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_guardia_salida");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_vehiculo");

                    b.Property<int?>("IdVisitante")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_visitante");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("placa");

                    b.Property<string>("TipoAcceso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_acceso");

                    b.HasKey("IdAcceso");

                    b.HasIndex("IdGarita");

                    b.HasIndex("IdGuardiaIngreso");

                    b.HasIndex("IdGuardiaSalida");

                    b.HasIndex("IdVehiculo");

                    b.HasIndex("IdVisitante");

                    b.ToTable("AccesoVehicular", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cargo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("IdCargo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Cargo", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Censo", b =>
                {
                    b.Property<int>("IdCenso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_censo");

                    b.Property<DateTime?>("FechaCenso")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_censo");

                    b.Property<int>("IdResidencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencia");

                    b.Property<int>("NumeroHabitantes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero_habitantes");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones");

                    b.HasKey("IdCenso");

                    b.HasIndex("IdResidencia");

                    b.ToTable("Censo", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Cluster", b =>
                {
                    b.Property<int>("IdCluster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cluster");

                    b.Property<int>("IdResidencial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencial");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("IdCluster");

                    b.HasIndex("IdResidencial", "Nombre")
                        .IsUnique();

                    b.ToTable("Cluster", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.ConceptoPago", b =>
                {
                    b.Property<int>("IdConceptoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_concepto_pago");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("IdConceptoPago");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ConceptoPago", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.DetalleRecibo", b =>
                {
                    b.Property<int>("IdDetalleRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_detalle_recibo");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdConceptoPago")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_concepto_pago");

                    b.Property<int>("IdRecibo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdRecibo");

                    b.Property<decimal>("MontoUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetalleRecibo");

                    b.HasIndex("IdConceptoPago");

                    b.HasIndex("IdRecibo");

                    b.ToTable("DetalleRecibo", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.EstadoCuenta", b =>
                {
                    b.Property<int>("IdEstadoCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdEstadoCuenta");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaGeneracion");

                    b.Property<int>("IdCasa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCasa");

                    b.Property<int>("IdResidencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencia");

                    b.Property<decimal?>("SaldoPendiente")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("SaldoPendiente");

                    b.Property<decimal?>("TotalPagado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TotalPagado");

                    b.HasKey("IdEstadoCuenta");

                    b.HasIndex("IdResidencia");

                    b.ToTable("EstadosCuenta", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Garita", b =>
                {
                    b.Property<int>("IdGarita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_garita");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activa");

                    b.Property<int?>("IdCluster")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cluster");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdGarita");

                    b.HasIndex("IdCluster");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Garita", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Guardia", b =>
                {
                    b.Property<int>("IdGuardia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdGuardia");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Activo");

                    b.Property<string>("Dpi")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("DPI");

                    b.Property<DateTime?>("FechaContratacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaContratacion");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("genero");

                    b.Property<int>("IdResidencial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencial");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefono");

                    b.Property<string>("Turno")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("Turno");

                    b.HasKey("IdGuardia");

                    b.HasIndex("Dpi")
                        .IsUnique();

                    b.HasIndex("IdResidencial");

                    b.ToTable("Guardia", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Inquilino", b =>
                {
                    b.Property<int>("IdInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_inquilino");

                    b.Property<string>("Dpi")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("dpi");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado_civil");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoLicencia")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_licencia");

                    b.HasKey("IdInquilino");

                    b.HasIndex("Dpi")
                        .IsUnique();

                    b.ToTable("Inquilino", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.JuntaDirectiva", b =>
                {
                    b.Property<int>("IdJuntaDirectiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_junta_directiva");

                    b.Property<int?>("AnioFin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anio_fin");

                    b.Property<int>("AnioInicio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anio_inicio");

                    b.Property<int>("IdCluster")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cluster");

                    b.HasKey("IdJuntaDirectiva");

                    b.HasIndex("IdCluster", "AnioInicio")
                        .IsUnique();

                    b.ToTable("JuntaDirectiva", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.MiembroJunta", b =>
                {
                    b.Property<int>("IdMiembroJunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_miembro_junta");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdCargo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cargo");

                    b.Property<int>("IdJuntaDirectiva")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_junta_directiva");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_propietario");

                    b.HasKey("IdMiembroJunta");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdPropietario");

                    b.HasIndex("IdJuntaDirectiva", "IdCargo")
                        .IsUnique();

                    b.HasIndex("IdJuntaDirectiva", "IdPropietario")
                        .IsUnique();

                    b.ToTable("MiembroJunta", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Multa", b =>
                {
                    b.Property<int>("IdMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdMulta");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Concepto");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("Fecha");

                    b.Property<int>("IdCasa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCasa");

                    b.Property<int>("IdCluster")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cluster");

                    b.Property<int>("IdResidencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencia");

                    b.Property<int?>("IdTipoMulta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_tipo_multa");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Monto");

                    b.Property<bool>("Pagada")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Pagada");

                    b.HasKey("IdMulta");

                    b.HasIndex("IdResidencia");

                    b.HasIndex("IdTipoMulta");

                    b.HasIndex("IdCluster", "IdResidencia");

                    b.ToTable("Multa", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.PagoMantenimiento", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPago");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaPago");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("FormaPago");

                    b.Property<int>("IdCasa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCasa");

                    b.Property<int>("IdResidencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencia");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Monto");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Observaciones");

                    b.HasKey("IdPago");

                    b.HasIndex("IdResidencia");

                    b.ToTable("PagosMantenimiento", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.PagoMulta", b =>
                {
                    b.Property<int>("IdPagoMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPagoMulta");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaPago");

                    b.Property<int>("IdMulta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdMulta");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("MontoPagado");

                    b.HasKey("IdPagoMulta");

                    b.HasIndex("IdMulta");

                    b.ToTable("PagoMulta", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.PersonaNoGrata", b =>
                {
                    b.Property<int>("IdPNG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPNG");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Activo");

                    b.Property<string>("Dpi")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("DPI");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaRegistro");

                    b.Property<int>("IdResidencial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencial");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Motivo");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreCompleto");

                    b.HasKey("IdPNG");

                    b.HasIndex("IdResidencial");

                    b.ToTable("PersonaNoGrata", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Propietario", b =>
                {
                    b.Property<int>("IdPropietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_propietario");

                    b.Property<string>("Dpi")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("dpi");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado_civil");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoLicencia")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_licencia");

                    b.HasKey("IdPropietario");

                    b.HasIndex("Dpi")
                        .IsUnique();

                    b.ToTable("Propietario", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Recibo", b =>
                {
                    b.Property<int>("IdRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdRecibo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("Fecha");

                    b.Property<int>("IdPago")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPago");

                    b.Property<string>("NumeroRecibo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("NumeroRecibo");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Total");

                    b.HasKey("IdRecibo");

                    b.HasIndex("IdPago");

                    b.ToTable("Recibos", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.RegistroVisita", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdRegistro");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaIngreso");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaSalida");

                    b.Property<int>("IdCasa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCasa");

                    b.Property<int?>("IdGarita")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_garita");

                    b.Property<int>("IdGuardiaIngreso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdGuardiaIngreso");

                    b.Property<int?>("IdGuardiaSalida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdGuardiaSalida");

                    b.Property<int>("IdResidencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencia");

                    b.Property<int>("IdVisitante")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVisitante");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Motivo");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdGarita");

                    b.HasIndex("IdGuardiaIngreso");

                    b.HasIndex("IdGuardiaSalida");

                    b.HasIndex("IdResidencia");

                    b.HasIndex("IdVisitante");

                    b.ToTable("RegistroVisita", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Residencia", b =>
                {
                    b.Property<int>("IdResidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<int>("IdCluster")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cluster");

                    b.Property<int?>("IdInquilino")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_inquilino");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_propietario");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.HasKey("IdResidencia");

                    b.HasIndex("IdInquilino");

                    b.HasIndex("IdPropietario");

                    b.HasIndex("IdCluster", "Numero")
                        .IsUnique();

                    b.ToTable("Residencia", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Residencial", b =>
                {
                    b.Property<int>("IdResidencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencial");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<int?>("CantidadViviendas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad_viviendas");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("departamento");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaInicioAdministracion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_inicio_administracion");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("municipio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("IdResidencial");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Residencial", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.TarjetaIntegracionPagos", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdMovimiento");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("Fecha");

                    b.Property<int>("IdCasa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCasa");

                    b.Property<int>("IdResidencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencia");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Monto");

                    b.Property<string>("Referencia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Referencia");

                    b.Property<string>("TipoMovimiento")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("TipoMovimiento");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdResidencia");

                    b.ToTable("TarjetaIntegracionPagos", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.TipoMulta", b =>
                {
                    b.Property<int>("IdTipoMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_tipo_multa");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("MontoBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_base");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoMulta");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoMulta", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.TurnoGuardia", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_turno");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdGarita")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_garita");

                    b.Property<int>("IdGuardia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_guardia");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdGarita");

                    b.HasIndex("IdGuardia");

                    b.ToTable("TurnoGuardia", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_vehiculo");

                    b.Property<int?>("Anio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anio");

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<int>("IdResidencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencia");

                    b.Property<string>("Linea")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("linea");

                    b.Property<string>("Marca")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("marca");

                    b.Property<string>("NumeroTarjeta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("numero_tarjeta");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("placa");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("IdResidencia");

                    b.HasIndex("NumeroTarjeta")
                        .IsUnique();

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculo", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.VehiculoNoPermitido", b =>
                {
                    b.Property<int>("IdVNP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVNP");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Activo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaRegistro");

                    b.Property<int>("IdResidencial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_residencial");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Motivo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Placa");

                    b.HasKey("IdVNP");

                    b.HasIndex("IdResidencial");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("VehiculoNoPermitido", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.Visitante", b =>
                {
                    b.Property<int>("IdVisitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVisitante");

                    b.Property<string>("Dpi")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("DPI");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Empresa");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("Placa")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Placa");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefono");

                    b.HasKey("IdVisitante");

                    b.ToTable("Visitante", (string)null);
                });

            modelBuilder.Entity("ARSAN_Web.Models.AccesoVehicular", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Garita", "Garita")
                        .WithMany("Accesos")
                        .HasForeignKey("IdGarita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.Guardia", "GuardiaIngreso")
                        .WithMany("AccesosIngreso")
                        .HasForeignKey("IdGuardiaIngreso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.Guardia", "GuardiaSalida")
                        .WithMany("AccesosSalida")
                        .HasForeignKey("IdGuardiaSalida")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ARSAN_Web.Models.Vehiculo", "Vehiculo")
                        .WithMany("Accesos")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ARSAN_Web.Models.Visitante", "Visitante")
                        .WithMany("Accesos")
                        .HasForeignKey("IdVisitante")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Garita");

                    b.Navigation("GuardiaIngreso");

                    b.Navigation("GuardiaSalida");

                    b.Navigation("Vehiculo");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Censo", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencia", "Residencia")
                        .WithMany("Censos")
                        .HasForeignKey("IdResidencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencia");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Cluster", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencial", "Residencial")
                        .WithMany("Clusters")
                        .HasForeignKey("IdResidencial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencial");
                });

            modelBuilder.Entity("ARSAN_Web.Models.DetalleRecibo", b =>
                {
                    b.HasOne("ARSAN_Web.Models.ConceptoPago", "ConceptoPago")
                        .WithMany("DetallesRecibo")
                        .HasForeignKey("IdConceptoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.Recibo", "Recibo")
                        .WithMany("Detalles")
                        .HasForeignKey("IdRecibo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConceptoPago");

                    b.Navigation("Recibo");
                });

            modelBuilder.Entity("ARSAN_Web.Models.EstadoCuenta", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencia", "Residencia")
                        .WithMany()
                        .HasForeignKey("IdResidencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencia");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Garita", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Cluster", "Cluster")
                        .WithMany("Garitas")
                        .HasForeignKey("IdCluster")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Guardia", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencial", "Residencial")
                        .WithMany("Guardias")
                        .HasForeignKey("IdResidencial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencial");
                });

            modelBuilder.Entity("ARSAN_Web.Models.JuntaDirectiva", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Cluster", "Cluster")
                        .WithMany("JuntasDirectivas")
                        .HasForeignKey("IdCluster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("ARSAN_Web.Models.MiembroJunta", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Cargo", "Cargo")
                        .WithMany("MiembrosJunta")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.JuntaDirectiva", "JuntaDirectiva")
                        .WithMany("Miembros")
                        .HasForeignKey("IdJuntaDirectiva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.Propietario", "Propietario")
                        .WithMany("MiembrosJunta")
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("JuntaDirectiva");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Multa", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencia", "Residencia")
                        .WithMany()
                        .HasForeignKey("IdResidencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.TipoMulta", "TipoMulta")
                        .WithMany("Multas")
                        .HasForeignKey("IdTipoMulta");

                    b.Navigation("Residencia");

                    b.Navigation("TipoMulta");
                });

            modelBuilder.Entity("ARSAN_Web.Models.PagoMantenimiento", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencia", "Residencia")
                        .WithMany()
                        .HasForeignKey("IdResidencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencia");
                });

            modelBuilder.Entity("ARSAN_Web.Models.PagoMulta", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Multa", "Multa")
                        .WithMany("PagosMulta")
                        .HasForeignKey("IdMulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Multa");
                });

            modelBuilder.Entity("ARSAN_Web.Models.PersonaNoGrata", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencial", "Residencial")
                        .WithMany("PersonasNoGratas")
                        .HasForeignKey("IdResidencial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencial");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Recibo", b =>
                {
                    b.HasOne("ARSAN_Web.Models.PagoMantenimiento", "Pago")
                        .WithMany("Recibos")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("ARSAN_Web.Models.RegistroVisita", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Garita", "Garita")
                        .WithMany("RegistrosVisita")
                        .HasForeignKey("IdGarita");

                    b.HasOne("ARSAN_Web.Models.Guardia", "GuardiaIngreso")
                        .WithMany("RegistrosIngreso")
                        .HasForeignKey("IdGuardiaIngreso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.Guardia", "GuardiaSalida")
                        .WithMany("RegistrosSalida")
                        .HasForeignKey("IdGuardiaSalida")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ARSAN_Web.Models.Residencia", "Residencia")
                        .WithMany()
                        .HasForeignKey("IdResidencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.Visitante", "Visitante")
                        .WithMany("RegistrosVisita")
                        .HasForeignKey("IdVisitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garita");

                    b.Navigation("GuardiaIngreso");

                    b.Navigation("GuardiaSalida");

                    b.Navigation("Residencia");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Residencia", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Cluster", "Cluster")
                        .WithMany("Residencias")
                        .HasForeignKey("IdCluster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.Inquilino", "Inquilino")
                        .WithMany("Residencias")
                        .HasForeignKey("IdInquilino");

                    b.HasOne("ARSAN_Web.Models.Propietario", "Propietario")
                        .WithMany("Residencias")
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");

                    b.Navigation("Inquilino");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("ARSAN_Web.Models.TarjetaIntegracionPagos", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencia", "Residencia")
                        .WithMany()
                        .HasForeignKey("IdResidencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencia");
                });

            modelBuilder.Entity("ARSAN_Web.Models.TurnoGuardia", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Garita", "Garita")
                        .WithMany("Turnos")
                        .HasForeignKey("IdGarita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARSAN_Web.Models.Guardia", "Guardia")
                        .WithMany("Turnos")
                        .HasForeignKey("IdGuardia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garita");

                    b.Navigation("Guardia");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Vehiculo", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencia", "Residencia")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdResidencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencia");
                });

            modelBuilder.Entity("ARSAN_Web.Models.VehiculoNoPermitido", b =>
                {
                    b.HasOne("ARSAN_Web.Models.Residencial", "Residencial")
                        .WithMany("VehiculosNoPermitidos")
                        .HasForeignKey("IdResidencial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residencial");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Cargo", b =>
                {
                    b.Navigation("MiembrosJunta");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Cluster", b =>
                {
                    b.Navigation("Garitas");

                    b.Navigation("JuntasDirectivas");

                    b.Navigation("Residencias");
                });

            modelBuilder.Entity("ARSAN_Web.Models.ConceptoPago", b =>
                {
                    b.Navigation("DetallesRecibo");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Garita", b =>
                {
                    b.Navigation("Accesos");

                    b.Navigation("RegistrosVisita");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Guardia", b =>
                {
                    b.Navigation("AccesosIngreso");

                    b.Navigation("AccesosSalida");

                    b.Navigation("RegistrosIngreso");

                    b.Navigation("RegistrosSalida");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Inquilino", b =>
                {
                    b.Navigation("Residencias");
                });

            modelBuilder.Entity("ARSAN_Web.Models.JuntaDirectiva", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Multa", b =>
                {
                    b.Navigation("PagosMulta");
                });

            modelBuilder.Entity("ARSAN_Web.Models.PagoMantenimiento", b =>
                {
                    b.Navigation("Recibos");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Propietario", b =>
                {
                    b.Navigation("MiembrosJunta");

                    b.Navigation("Residencias");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Recibo", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Residencia", b =>
                {
                    b.Navigation("Censos");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Residencial", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("Guardias");

                    b.Navigation("PersonasNoGratas");

                    b.Navigation("VehiculosNoPermitidos");
                });

            modelBuilder.Entity("ARSAN_Web.Models.TipoMulta", b =>
                {
                    b.Navigation("Multas");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Vehiculo", b =>
                {
                    b.Navigation("Accesos");
                });

            modelBuilder.Entity("ARSAN_Web.Models.Visitante", b =>
                {
                    b.Navigation("Accesos");

                    b.Navigation("RegistrosVisita");
                });
#pragma warning restore 612, 618
        }
    }
}
